# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

_defaults: &defaults
    docker:
      - image: circleci/golang:1.13

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: go-mod-v3-{{ checksum "go.sum" }}
      - run:
          name: Install tools
          command: |
            go vet ./...
            go get -u github.com/onsi/ginkgo/ginkgo
            go get -u github.com/onsi/gomega/...
            go get -u golang.org/x/crypto/...
            go get -u github.com/loongy/covermerge
            go get -u github.com/mattn/goveralls
            go get -u golang.org/x/lint/golint
            CI=true /go/bin/ginkgo -v --race --cover --coverprofile coverprofile.out ./...
            /go/bin/covermerge            \
              block/coverprofile.out      \
              process/coverprofile.out    \
              replica/coverprofile.out    \
              coverprofile.out > coverprofile.out
            sed -i '/marshal.go/d' coverprofile.out
            /go/bin/goveralls -coverprofile=coverprofile.out -service=circleci -repotoken $COVERALLS_REPO_TOKEN
          no_output_timeout: 40m
      - save_cache:
          key: go-mod-v3-{{ checksum "go.sum" }}
          paths:
            - "~/go"
      - run:
          name: Run linter
          command: golint ./...

workflows:
  version: 2.1
  build:
    jobs:
    - build
